#!/sbin/ext/busybox sh

mount -t rootfs -o remount,rw rootfs
/sbin/ext/busybox ln -s /sbin/recovery /sbin/busybox

mount -t rfs -o rw,noatime,nodiratime,check=no /dev/block/stl11 /cache >> /dev/null 2>&1
mount -t ext4 -o rw,noatime,nodiratime,noauto_da_alloc,barrier=1 /dev/block/stl11 /cache >> /dev/null 2>&1

/sbin/ext/busybox ln -s /sbin/busybox /sbin/sh

start adbd

if [ -f /cache/recovery/command ];
then
  cp /res/keys-samsung /res/keys
  recovery-samsung
else
  echo 1 > /sbin/recovery-is-running
  recovery
fi;
